---
title: "Peak Cut Off"
author: "Steven Yu"
date: "2025-07-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

## Peak Anaylsis

#### Loading Packages 
```{r load packages}
library(tidyverse)
library(readr)
library(edgeR)
library(ComplexHeatmap)
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)
library(viridis)
library(DT)
library(kableExtra)
library(genomation)
library(GenomicRanges)
library(chromVAR) ## For FRiP analysis and differential analysis
library(DESeq2) ## For differential analysis section
library(ggpubr) ## For customizing figures
library(corrplot) ## For correlation plot
library(ggpmisc)
library(gcplyr)
library(Rsubread)
```

#### Data Initialization
```{r init}
sampleinfo <- read_delim("data/sample_info.tsv", delim = "\t")
```

#### Functions
```{r functions}
drug_pal <- c("#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","#41B333")
pca_plot <-
  function(df,
           col_var = NULL,
           shape_var = NULL,
           title = "") {
    ggplot(df) + geom_point(aes_string(
      x = "PC1",
      y = "PC2",
      color = col_var,
      shape = shape_var
    ),
    size = 5) +
      labs(title = title, x = "PC 1", y = "PC 2") +
      scale_color_manual(values = c(
        "#8B006D",
        "#DF707E",
        "#F1B72B",
        "#3386DD",
        "#707031",
        "#41B333"
      ))
  }
pca_var_plot <- function(pca) {
  # x: class == prcomp
  pca.var <- pca$sdev ^ 2
  pca.prop <- pca.var / sum(pca.var)
  var.plot <-
    qplot(PC, prop, data = data.frame(PC = 1:length(pca.prop),
                                      prop = pca.prop)) +
    labs(title = 'Variance contributed by each PC',
         x = 'PC', y = 'Proportion of variance')
  plot(var.plot)
}

calc_pca <- function(x) {
  # Performs principal components analysis with prcomp
  # x: a sample-by-gene numeric matrix
  prcomp(x, scale. = TRUE, retx = TRUE)
}

get_regr_pval <- function(mod) {
  # Returns the p-value for the Fstatistic of a linear model
  # mod: class lm
  stopifnot(class(mod) == "lm")
  fstat <- summary(mod)$fstatistic
  pval <- 1 - pf(fstat[1], fstat[2], fstat[3])
  return(pval)
}

plot_versus_pc <- function(df, pc_num, fac) {
  # df: data.frame
  # pc_num: numeric, specific PC for plotting
  # fac: column name of df for plotting against PC
  pc_char <- paste0("PC", pc_num)
  # Calculate F-statistic p-value for linear model
  pval <- get_regr_pval(lm(df[, pc_char] ~ df[, fac]))
  if (is.numeric(df[, f])) {
    ggplot(df, aes_string(x = f, y = pc_char)) + geom_point() +
      geom_smooth(method = "lm") + labs(title = sprintf("p-val: %.2f", pval))
  } else {
    ggplot(df, aes_string(x = f, y = pc_char)) + geom_boxplot() +
      labs(title = sprintf("p-val: %.2f", pval))
  }
}
x_axis_labels = function(labels, every_nth = 1, ...) {
  axis(side = 1,
       at = seq_along(labels),
       labels = F)
  text(
    x = (seq_along(labels))[seq_len(every_nth) == 1],
    y = par("usr")[3] - 0.075 * (par("usr")[4] - par("usr")[3]),
    labels = labels[seq_len(every_nth) == 1],
    xpd = TRUE,
    ...
  )
}
```

### Peak Widths

#### Peak Width Function
```{r peak withs}
histone_list <- c("H3K27ac", "H3K27me3", "H3K9me3", "H3K36me3")
get_peak_widths_long_split <- function(histone, var) {
  path <- file.path("data/peaks", histone)
  if (var == "all") {
    file_list = list.files(path = path, pattern = "FINAL_merged.bed", full.names = TRUE)
  } else if (histone == "H3K27ac"){
    file_list = list.files(path = path, pattern = "picard_peaks.narrowPeak$", full.names = TRUE)
  } else {
    file_list = list.files(path = path, pattern = paste0(var,"_peaks.(narrowPeak|broadPeak)$", sep=""), full.names = TRUE)
  }
  process_peak <- function(file_path, label) {
    filename <- basename(file_path)
    peak_df <- fread(file_path, header = FALSE) %>%
      transmute(
        row = row_number(),
        width = abs(V3 - V2),
        file = paste0(histone, "-", filename),
        group = label
      )
    return(peak_df)
  }
  peak_list <- list(map(file_list, process_peak, label = var)) %>% flatten()
  bind_rows(peak_list)
}
```

#### Broad Visualization
```{r picard broad length}
all_peak_widths <- purrr::map_df(histone_list, get_peak_widths_long_split, var = "picard_broad")

anno_peak_width_long <- all_peak_widths %>% 
  mutate(file= gsub("_picard_broad_peaks.broadPeak","",file)) %>%
  separate_wider_delim(., cols=file, delim="-",names=c("histone","sample")) %>% 
  left_join(sampleinfo, by =c("sample"="Library ID"))

anno_peak_width_long %>%
  # distinct(histone)
  ggplot(.,aes(x=histone, y = width, fill = histone))+
  geom_violin()+
  # scale_fill_viridis_a(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
  #   scale_color_viridis_a(discrete = TRUE, begin = 0.1, end = 0.9) +
    scale_y_continuous(trans = "log", breaks = c(400, 3000, 22000)) +
    theme_bw(base_size = 18) +
    ylab("Width of Peaks") +
    xlab("")+
  ggtitle("Width of all peaks with Broad Peaks")
```

#### Broad as Narrow Visualization
```{r picard narrow length}
all_peak_widths <- purrr::map_df(histone_list, get_peak_widths_long_split, var = "picard_narrow")

anno_peak_width_long <- all_peak_widths %>% 
  mutate(file= gsub("_picard_narrow_peaks.narrowPeak","",file)) %>%
  separate_wider_delim(., cols=file, delim="-",names=c("histone","sample")) %>% 
  left_join(sampleinfo, by =c("sample"="Library ID"))

anno_peak_width_long %>%
  # distinct(histone)
  ggplot(.,aes(x=histone, y = width, fill = histone))+
  geom_violin()+
  # scale_fill_viridis_a(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
  #   scale_color_viridis_a(discrete = TRUE, begin = 0.1, end = 0.9) +
    scale_y_continuous(trans = "log", breaks = c(400, 3000, 22000)) +
    theme_bw(base_size = 18) +
    ylab("Width of Peaks") +
    xlab("")+
  ggtitle("Width of all peaks with Broad as Narrow")
```

#### Broad as Narrow Stringent Visualization
```{r stringent narrow length}
all_peak_widths <- purrr::map_df(histone_list, get_peak_widths_long_split, var = "1e3_narrow")

anno_peak_width_long <- all_peak_widths %>% 
  mutate(file= gsub("_1e3_narrow_peaks.narrowPeak","",file)) %>%
  separate_wider_delim(., cols=file, delim="-",names=c("histone","sample")) %>% 
  left_join(sampleinfo, by =c("sample"="Library ID"))

anno_peak_width_long %>%
  # distinct(histone)
  ggplot(.,aes(x=histone, y = width, fill = histone))+
  geom_violin()+
  # scale_fill_viridis_a(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
  #   scale_color_viridis_a(discrete = TRUE, begin = 0.1, end = 0.9) +
    scale_y_continuous(trans = "log", breaks = c(400, 3000, 22000)) +
    theme_bw(base_size = 18) +
    ylab("Width of Peaks") +
    xlab("")+
  ggtitle("Width of all peaks with Broad as Stringent Narrow")
```

#### Broad as Stringent Narrow without Picard
```{r FINAL}
all_peak_widths <- purrr::map_df(histone_list, get_peak_widths_long_split, var = "FINAL")

anno_peak_width_long <- all_peak_widths %>% 
  mutate(file= gsub("_picard_narrow_peaks.narrowPeak","",file)) %>%
  separate_wider_delim(., cols=file, delim="-",names=c("histone","sample")) %>% 
  left_join(sampleinfo, by =c("sample"="Library ID"))

anno_peak_width_long %>%
  # distinct(histone)
  ggplot(.,aes(x=histone, y = width, fill = histone))+
  geom_violin()+
  # scale_fill_viridis_a(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
  #   scale_color_viridis_a(discrete = TRUE, begin = 0.1, end = 0.9) +
    scale_y_continuous(trans = "log", breaks = c(400, 3000, 22000)) +
    theme_bw(base_size = 18) +
    ylab("Width of Peaks") +
    xlab("")+
  ggtitle("0.001 Narrow Without Picard")
```

```{r Merged}
all_peak_widths <- purrr::map_df(histone_list, get_peak_widths_long_split, var = "all")

anno_peak_width_long <- all_peak_widths %>% 
  mutate(file= gsub("_FINAL_merged.bed","",file)) %>%
  separate_wider_delim(., cols=file, delim="-",names=c("histone","sample")) %>% 
  left_join(sampleinfo, by =c("sample"="Library ID"))

anno_peak_width_long %>%
  # distinct(histone)
  ggplot(.,aes(x=histone, y = width, fill = histone))+
  geom_violin()+
  # scale_fill_viridis_a(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
  #   scale_color_viridis_a(discrete = TRUE, begin = 0.1, end = 0.9) +
    scale_y_continuous(trans = "log", breaks = c(400, 3000, 22000)) +
    theme_bw(base_size = 18) +
    ylab("Width of Peaks") +
    xlab("")+
  ggtitle("Merged")
```
